spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ikunycj?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml        # ??mybatis?xml????
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??sql??????

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??sql??????